//testing basic dead code elimination

left=def test(x:Int): Int = { return x; }
right=def test(x:Int): Int = { var y = 100; return x; }

//fails, right side generated bytecode produces code for storing 100 at y
// also generates a local 
